DEFAULT_PROFIT_MARGIN = 3.5
DEFAULT_SLEEP_INTERVAL = 90
DEFAULT_INVESTMENT_AMOUNT = 25
DEFAULT_MAX_BUY_PRICE = 2.5
DEFAULT_LOT_SIZE_FILTER = "LOT_SIZE"
DEFAULT_VALIDATION_MIN_SCORE = 4
DEFAULT_STOP_LOSS_MARGIN = 12